(** [Kb_regen] — see [kb_regen.mli]. *)

let target_files = [
  "INDEX.md";
  "GLOSSARY.md";
  "spec/data-model.md";
  "spec/algorithms.md";
  "properties/functional.md";
  "properties/edge-cases.md";
]

let aspects_for = function
  | "INDEX.md" ->
      [ "goal"; "inputs_outputs"; "errors"; "fs_contract";
        "examples_accept"; "examples_refuse"; "out_of_scope" ]
  | "GLOSSARY.md" -> [ "goal"; "examples_accept" ]
  | "spec/data-model.md" -> [ "inputs_outputs"; "errors"; "fs_contract" ]
  | "spec/algorithms.md" -> [ "examples_accept"; "examples_refuse" ]
  | "properties/functional.md" ->
      [ "goal"; "inputs_outputs"; "errors"; "fs_contract";
        "examples_accept"; "examples_refuse" ]
  | "properties/edge-cases.md" -> [ "examples_refuse" ]
  | _ -> []

let aspect_value (c : Characterization.t) = function
  | "goal" -> c.goal
  | "inputs_outputs" ->
      Canonical_json.to_string
        (Characterization_json.io_schema_to_yojson c.inputs_outputs)
  | "errors" ->
      Canonical_json.to_string
        (`List (List.map Characterization_json.error_entry_to_yojson
                  c.errors))
  | "fs_contract" ->
      Canonical_json.to_string
        (Characterization_json.fs_contract_to_yojson c.fs_contract)
  | "examples_accept" ->
      Canonical_json.to_string
        (`List (List.map Characterization_json.acceptance_example_to_yojson
                  c.examples_accept))
  | "examples_refuse" ->
      Canonical_json.to_string
        (`List (List.map Characterization_json.refusing_example_to_yojson
                  c.examples_refuse))
  | "out_of_scope" ->
      String.concat "," c.out_of_scope
  | _ -> ""

let all_aspect_names = [
  "goal"; "inputs_outputs"; "errors"; "fs_contract";
  "examples_accept"; "examples_refuse"; "out_of_scope";
]

let diff_aspects ~prev ~current =
  match prev with
  | None -> all_aspect_names
  | Some p ->
      List.filter (fun a ->
        aspect_value p a <> aspect_value current a) all_aspect_names

let files_affected_by ~changed =
  List.filter (fun f ->
    let aspects = aspects_for f in
    List.exists (fun a -> List.mem a aspects) changed
  ) target_files

(* --- ownership detection (P14, T18) --- *)

let extract_content_hash body =
  (* Frontmatter is the first YAML block delimited by lines exactly
     equal to "---". Look for [content_hash: <value>] inside it. *)
  let lines = String.split_on_char '\n' body in
  let rec collect_fm = function
    | [] -> []
    | "---" :: rest ->
        let rec until_end acc = function
          | [] -> List.rev acc
          | "---" :: _ -> List.rev acc
          | l :: tl -> until_end (l :: acc) tl
        in
        until_end [] rest
    | _ :: tl -> collect_fm tl
  in
  let fm_lines = collect_fm lines in
  let prefix = "content_hash:" in
  List.find_map (fun l ->
    let l' = String.trim l in
    if String.length l' > String.length prefix
       && String.sub l' 0 (String.length prefix) = prefix then
      Some (String.trim
              (String.sub l' (String.length prefix)
                 (String.length l' - String.length prefix)))
    else None
  ) fm_lines

let body_after_frontmatter body =
  let lines = String.split_on_char '\n' body in
  let rec drop_fm seen = function
    | [] -> []
    | "---" :: rest when not seen -> drop_fm true rest
    | "---" :: rest when seen -> rest
    | _ :: rest when seen -> drop_fm seen rest
    | _ :: rest -> drop_fm seen rest
  in
  String.concat "\n" (drop_fm false lines)

let is_owned_by_k4k ~k4k_dir ~rel_path =
  let path = Filename.concat k4k_dir rel_path in
  if not (Sys.file_exists path) then true
  else
    let body = Persist.read_file path in
    match extract_content_hash body with
    | None -> false  (* user-authored: no recorded hash *)
    | Some recorded ->
        let actual =
          Persist.sha256_hex (body_after_frontmatter body) in
        String.equal recorded actual

(* --- rendering (deterministic, no agent call needed for v0) --- *)

let frontmatter ~id ~typ ~summary ~domain ~content_hash =
  Printf.sprintf
    "---\n\
     id: %s\n\
     type: %s\n\
     summary: %s\n\
     domain: %s\n\
     last-updated: 2026-05-02\n\
     owner: k4k\n\
     content_hash: %s\n\
     ---\n"
    id typ summary domain content_hash

let body_for rel_path (d : Characterization.t) =
  match rel_path with
  | "INDEX.md" ->
      Printf.sprintf
        "# Target program — index\n\n\
         Generated by k4k from the formalized characterization.\n\n\
         - GLOSSARY.md\n\
         - spec/data-model.md\n\
         - spec/algorithms.md\n\
         - properties/functional.md\n\
         - properties/edge-cases.md\n\n\
         ## Goal\n\n%s\n" d.goal
  | "GLOSSARY.md" ->
      let names = List.map (fun (a : Characterization.acceptance_example) ->
        a.name) d.examples_accept in
      Printf.sprintf
        "# Glossary\n\n\
         - **goal**: %s\n\
         - **acceptance examples**: %s\n"
        d.goal (String.concat ", " names)
  | "spec/data-model.md" ->
      Printf.sprintf
        "# Target data model\n\n\
         ## Inputs/outputs\n\n\
         argv (%d), exit_codes (%d)\n\n\
         ## Errors\n\n%s\n\n\
         ## FS contract\n\n\
         reads (%d), writes (%d), creates (%d)\n"
        (List.length d.inputs_outputs.argv)
        (List.length d.inputs_outputs.exit_codes)
        (String.concat "\n" (List.map (fun (e : Characterization.error_entry) ->
           Printf.sprintf "- %s: %s" e.id e.when_) d.errors))
        (List.length d.fs_contract.reads)
        (List.length d.fs_contract.writes)
        (List.length d.fs_contract.creates)
  | "spec/algorithms.md" ->
      Printf.sprintf
        "# Target algorithms\n\n\
         %d acceptance examples, %d refusing examples.\n"
        (List.length d.examples_accept)
        (List.length d.examples_refuse)
  | "properties/functional.md" ->
      let props = Property.from_characterization d in
      let entry (p : Property.t) =
        Printf.sprintf "### %s\n- Statement: %s\n" p.id p.statement in
      Printf.sprintf
        "# Functional properties (target)\n\n%s\n"
        (String.concat "\n" (List.map entry props))
  | "properties/edge-cases.md" ->
      let entry (r : Characterization.refusing_example) =
        Printf.sprintf "- %s: rejected with %s" r.name r.expect_error in
      Printf.sprintf
        "# Edge cases (target)\n\n%s\n"
        (String.concat "\n" (List.map entry d.examples_refuse))
  | _ -> "# (unknown target-KB file)\n"

let kind_of rel_path =
  match rel_path with
  | "INDEX.md" -> ("INDEX", "index", "Target program KB index", "target")
  | "GLOSSARY.md" -> ("GLOSSARY", "concept", "Target program glossary", "target")
  | "spec/data-model.md" ->
      ("spec.data-model", "spec", "Target data-model", "spec")
  | "spec/algorithms.md" ->
      ("spec.algorithms", "spec", "Target algorithms", "spec")
  | "properties/functional.md" ->
      ("properties.functional", "spec", "Target functional properties",
       "properties")
  | "properties/edge-cases.md" ->
      ("properties.edge-cases", "spec", "Target edge cases", "properties")
  | _ -> (rel_path, "concept", rel_path, "target")

let render_file ~rel_path ~d =
  let body = body_for rel_path d in
  let hash = Persist.sha256_hex body in
  let (id, typ, summary, domain) = kind_of rel_path in
  frontmatter ~id ~typ ~summary ~domain ~content_hash:hash ^ body

let write_one ~k4k_dir ~rel_path ~d ~logger =
  if is_owned_by_k4k ~k4k_dir ~rel_path then begin
    let path = Filename.concat k4k_dir rel_path in
    Persist.atomic_write ~path (render_file ~rel_path ~d);
    Logger.info logger "kb-regen.write"
      (`Assoc [ "file", `String rel_path ])
  end else
    Logger.info logger "ownership.flip"
      (`Assoc [ "file", `String rel_path ])

let regen_set ~k4k_dir ~current_d ~logger files =
  Logger.info logger "kb-regen.start"
    (`Assoc [ "files", `Int (List.length files) ]);
  List.iter (fun f -> write_one ~k4k_dir ~rel_path:f ~d:current_d ~logger)
    files;
  Logger.info logger "kb-regen.complete"
    (`Assoc [ "files", `Int (List.length files) ])

let regen ~k4k_dir ~prev_d ~current_d ~logger =
  let changed = diff_aspects ~prev:prev_d ~current:current_d in
  let files = files_affected_by ~changed in
  regen_set ~k4k_dir ~current_d ~logger files

let regen_full ~k4k_dir ~current_d ~logger =
  regen_set ~k4k_dir ~current_d ~logger target_files
