(** [Kb_render] — see [kb_render.mli]. *)

let frontmatter ~id ~typ ~summary ~domain ~content_hash =
  Printf.sprintf
    "---\n\
     id: %s\n\
     type: %s\n\
     summary: %s\n\
     domain: %s\n\
     last-updated: 2026-05-02\n\
     owner: k4k\n\
     content_hash: %s\n\
     ---\n"
    id typ summary domain content_hash

let body_index (d : Characterization.t) =
  Printf.sprintf
    "# Target program — index\n\n\
     Generated by k4k from the formalized characterization.\n\n\
     - GLOSSARY.md\n\
     - spec/data-model.md\n\
     - spec/algorithms.md\n\
     - properties/functional.md\n\
     - properties/edge-cases.md\n\n\
     ## Goal\n\n%s\n" d.goal

let body_glossary (d : Characterization.t) =
  let names = List.map (fun (a : Characterization.acceptance_example) ->
    a.name) d.examples_accept in
  Printf.sprintf
    "# Glossary\n\n\
     - **goal**: %s\n\
     - **acceptance examples**: %s\n"
    d.goal (String.concat ", " names)

let body_data_model (d : Characterization.t) =
  Printf.sprintf
    "# Target data model\n\n\
     ## Inputs/outputs\n\n\
     argv (%d), exit_codes (%d)\n\n\
     ## Errors\n\n%s\n\n\
     ## FS contract\n\n\
     reads (%d), writes (%d), creates (%d)\n"
    (List.length d.inputs_outputs.argv)
    (List.length d.inputs_outputs.exit_codes)
    (String.concat "\n" (List.map (fun (e : Characterization.error_entry) ->
       Printf.sprintf "- %s: %s" e.id e.when_) d.errors))
    (List.length d.fs_contract.reads)
    (List.length d.fs_contract.writes)
    (List.length d.fs_contract.creates)

let body_algorithms (d : Characterization.t) =
  Printf.sprintf
    "# Target algorithms\n\n\
     %d acceptance examples, %d refusing examples.\n"
    (List.length d.examples_accept)
    (List.length d.examples_refuse)

let body_functional (d : Characterization.t) =
  let props = Property.from_characterization d in
  let entry (p : Property.t) =
    Printf.sprintf "### %s\n- Statement: %s\n" p.id p.statement in
  Printf.sprintf
    "# Functional properties (target)\n\n%s\n"
    (String.concat "\n" (List.map entry props))

let body_edge_cases (d : Characterization.t) =
  let entry (r : Characterization.refusing_example) =
    Printf.sprintf "- %s: rejected with %s" r.name r.expect_error in
  Printf.sprintf
    "# Edge cases (target)\n\n%s\n"
    (String.concat "\n" (List.map entry d.examples_refuse))

let body_for rel_path d =
  match rel_path with
  | "INDEX.md" -> body_index d
  | "GLOSSARY.md" -> body_glossary d
  | "spec/data-model.md" -> body_data_model d
  | "spec/algorithms.md" -> body_algorithms d
  | "properties/functional.md" -> body_functional d
  | "properties/edge-cases.md" -> body_edge_cases d
  | _ -> "# (unknown target-KB file)\n"

let kind_of rel_path =
  match rel_path with
  | "INDEX.md" -> ("INDEX", "index", "Target program KB index", "target")
  | "GLOSSARY.md" -> ("GLOSSARY", "concept", "Target program glossary",
                      "target")
  | "spec/data-model.md" ->
      ("spec.data-model", "spec", "Target data-model", "spec")
  | "spec/algorithms.md" ->
      ("spec.algorithms", "spec", "Target algorithms", "spec")
  | "properties/functional.md" ->
      ("properties.functional", "spec", "Target functional properties",
       "properties")
  | "properties/edge-cases.md" ->
      ("properties.edge-cases", "spec", "Target edge cases", "properties")
  | _ -> (rel_path, "concept", rel_path, "target")

let render_file ~rel_path ~d =
  let body = body_for rel_path d in
  let hash = Persist.sha256_hex body in
  let (id, typ, summary, domain) = kind_of rel_path in
  frontmatter ~id ~typ ~summary ~domain ~content_hash:hash ^ body
